version: "3.8"

volumes:
  postgres:
    external: false

services:
  go-clean-architecture-app:
    build:
      context: .
      dockerfile: Dockerfile
      # GitHub credentials required to get private go repositories belong to organization.
      args:
        GITHUB_USERNAME: "your_github_username"
        GITHUB_TOKEN: "your_github_personal_access_token"
    image: go-clean-architecture:latest
    ports:
      - "8080:8080"
    environment:
      APP_ENVIRONMENT: "Development"
  postgres:
    image: postgres:14.2-bullseye
    ports:
      - "5433:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "go-clean-architecture"
      POSTGRES_PASSWORD: "your_db_password"
      POSTGRES_DB: "go-clean-architecture"
  redis:
    image: redis:6.2.6-bullseye
    ports:
      - "6380:6379"
